# strl+shift+f5 to update and apply configs

# Font settings 🅰️
# font_family      FantasqueSansM Nerd Font Mono Bold
font_family      JetBrainsMono Nerd Font Mono
font_size        12.0
italic_font      auto
bold_italic_font auto
bold_font        auto
# Colors 🎨
foreground #dddddd
background #0f0f0f
cursor     #115599

selection_foreground none
selection_background #44475a

# Transparency and padding 🌫️
background_opacity          0.80
blur = true
dynamic_background_opacity no
window_padding_width       4 

# Cursor & animation ✨
cursor_trail 1
cursor_shape beam

# Window settings 🪟
remember_window_size no
initial_window_width  800
initial_window_height 450
#linux_display_server  x11
confirm_os_window_close 0

# Scrolling 📜
scrollback_lines       1000
wheel_scroll_min_lines 1

# Audio 🔇
enable_audio_bell no

#keys mapping
map f11 toggle_fullscreen
map ctrl+shift+n new_os_window_with_cwd


